version: 2.1

jobs:
  build-test-linux:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uGkIYtXviCrn6fwm/9e/4RBK5GzKmWmJPp+CFgnig0M"
      - run:
          name: Add GitHub to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set up Git Config
          command: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"

      - run:
          name: Install CMake
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
            sudo apt-get install -y libgl1-mesa-dev mesa-common-dev libglu1-mesa-dev freeglut3-dev
      - run:
          name: Verify CMake installation
          command: cmake --version
      - run:
          name: Build with CMake
          command: |
            mkdir build
            cd build
            cmake -DBUILD_WITH_TESTS=1 ..
            cmake --build . --config Release -j8

  # New Windows job
  build-test-windows:
    machine:
      # Use Windows machine executor with version
      image: 'windows-server-2019-vs2019:2024.05.1'
      resource_class: windows.medium
      shell: powershell.exe
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uGkIYtXviCrn6fwm/9e/4RBK5GzKmWmJPp+CFgnig0M"
      - run:
          name: Add GitHub to known hosts
          shell: bash.exe
          command: |
            mv ~/.ssh/id_rsa_* ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Download and Install CMake
          command: |
            $ProgressPreference = "SilentlyContinue"
            Invoke-WebRequest -URI https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-win64-x64.zip -OutFile $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip
            Expand-Archive $Env:HOMEPATH\cmake-3.16.4-win64-x64.zip -DestinationPath $Env:HOMEPATH
      - run:
          name: Build with CMake
          command: |
            $cmakePath = "$Env:HOMEPATH\cmake-3.16.4-win64-x64\bin"
            $env:PATH += ";$cmakePath"
            cmake --version
            mkdir build
            cd build
            cmake -DBUILD_WITH_TESTS=1 ..
            cmake --build . --config Release -j8

  build-test-mac:

    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uGkIYtXviCrn6fwm/9e/4RBK5GzKmWmJPp+CFgnig0M"
      - run:
          name: Add GitHub to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set up Git Config
          command: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"

      - run:
          name: Install Dependencies
          command: |
            brew update
            brew install cmake
      - run:
          name: Verify CMake installation
          command: cmake --version
      - run:
          name: Build with CMake
          command: |
            mkdir build
            cd build
            cmake -DBUILD_WITH_TESTS=1 ..
            cmake --build . --config Release -j8

workflows:
  build-and-test-workflow:
    jobs:
      - build-test-linux
      - build-test-windows
      - build-test-mac